### PR TITLE
Get rid of old Point, Box, Sphere

### PR DESCRIPTION
**Pull request by aprokop**
@dalg24 I'm trying to get rid of the old geometries. I need your help.
One immediate failure is code like `Point(0, 0, 0)` or `Point(0.75, 0, 0)`. It probably has something to do with the deduction guides, as we only have. You are much better in C++ than I am. Do you have any suggestions?

### CODE REVIEW

**Comment by dalg24** [comment]
Let's talk and agree on the direction first.
I would like to eventually our current Point to become something like the hyper point but one caveat is that it would change the meaning of `Point{1., 2., 3.}` (we probably would not narrow to Point<3, float> any more).

**Comment by aprokop** [comment]
In the end, I want to have a single `Point`, `Box` and `Sphere`. I agree that they shouldn't narrow `double`. I don't know how to transition to it, though, without breaking backwards compatibility.

> I would like to eventually our current Point to become something like the hyper point

I'm not sure what you mean by this. Do you still envision having two separate classes?

**Comment by dalg24** [comment]
No, just one class but with the understanding that it will break backward
compatibility and that we probably should time it with a new major release
and the API v2

**Comment by aprokop** [comment]
Do you see a way to have one release where we deprecate the old `Point`, and promote the `ExperimentalHyperGeometry` to the regular `ArborX::` namespace to allow users to adjust? I don't currently see a way to do it. Which means that when we release 2.0, it's going to be an abrupt change to the users. Maybe it's fine, as I don't know how many do narrowing or use old constructors.

**Comment by aprokop** [comment]
We are also not careful about promoting `FloatingPoint` from the user data into our internal structures. So, at the moment, I don't think you can even construct a hierarchy based on the `double`, given that we don't have `GeometryTraits` to get the type out.

**Pull request closed without merging**
